from front.cli.cli_replay import CliReplay
from argparse import ArgumentParser
import pickle


parser = ArgumentParser(prog='replay for pacman saved game',
                        description='Replay the lastest file generated by default',
                        epilog='epilog')
parser.add_argument('-p', '--path',
                    help='path to the replay file',
                    default='last_replay.pkl')
args = parser.parse_args()

replay = pickle.load(open(args.path, 'rb'))
clireplay = CliReplay(replay)
