@startuml full

title Simulation cycle


actor Main
entity PacmanBrain
entity GhostBrain
database Perception
boundary PacmanGame

activate Main

Main -> PacmanGame : gather_state()
activate PacmanGame
Main <-- PacmanGame : tuple[tuple[str, Board, tuple[tuple[str, int, int]]]]
deactivate PacmanGame

group parallelism
    Main -> Main : mask_perception(Board, Agents)
end

Main -> Perception : time_step()
activate Perception
Main <-- Perception
Main -> Perception : update(Board, agents_seen)
Main <-- Perception
deactivate Perception
Main -> Main : strategy_computation()

group parallelism
    Main -> PacmanBrain : step(strategy, Peception)
    activate PacmanBrain
    Main <-- PacmanBrain : Action
    deactivate PacmanBrain
else
    Main -> GhostBrain : step(strategy, Peception)
    deactivate PacmanBrain
    activate GhostBrain
    Main <-- GhostBrain : Action
    deactivate GhostBrain
end

Main -> PacmanGame : step(Actions)
activate PacmanGame
Main <-- PacmanGame
deactivate PacmanGame

@enduml
